Use $* instead of $@ for string concatenation

diff --git a/torrential b/torrential
--- a/torrential
+++ b/torrential
@@ -120,7 +120,7 @@ ensure_enabled(){
 
 
 error(){
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
 }
 
 
@@ -149,7 +149,7 @@ firewall_state(){
 
 
 info(){
-    echo "INFO: $@"
+    echo "INFO: $*"
 }
 
 
